apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    env: dev
    app: travelbooking-ms
    layer: frontend
  name: dev-travelbooking-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: travelbooking.cloudgeek.in
      http:
        paths:
          -backend:
            serviceName:dev-cloudgeek-service
            serviceport:8080
           path:/