---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-travelbooking-ingress
  namespace: dev
  labels:
    env: dev
    app: travelbooking-ms
    layer: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: travelbooking.cloudgeek.in
      http:
        paths:
          -backend: |-
            serviceName:prod-cloudgeek-service servicePort:8080
            path:/
